Create endpoints save_to_read #30
fabricadesoftware-ifc/fabricaNews_backEnd pull request #48
Opened 2023-04-25 17:30 UTC by BrunnoDC

2023-04-27 20:03 UTC, ldmfabio requested changes
You need to change the name of model. The recommended is **SaveToRead**.

2023-04-27 20:03 UTC, ldmfabio commented on core/serializers/__init__.py
Pay attention to the name of model. The recommended is **SaveToRead**.

2023-05-04 19:19 UTC, eduardo-da-silva approved these changes

2023-05-04 19:21 UTC, ldmfabio approved these changes
Approved.

2023-05-04 19:22 UTC, merged