Development
fabricadesoftware-ifc/fabricaNews_backEnd pull request #55
Opened 2023-05-05 16:33 UTC by ldmfabio

Release Number 1

2023-05-05 16:34 UTC, eduardo-da-silva approved these changes

2023-05-07 14:05 UTC, ViniciusAcordiSoethe requested changes
Resolver o erro na `pdm.lock`, e o arquivo se encontra na `.gitignore` 

Possível problema arquivo criado antes da `.gitignore`

2023-05-07 14:05 UTC, ViniciusAcordiSoethe commented on pdm.lock
encontrado erro na branch `development` nesse arquivo `pdm.lock`
linha 1 deixa claro que o arquivo foi upado sem resolver o conflito adicionando caracteres ilegíveis pelo pdm nas linha 1, 93 e 498 no arquivo tornando impossível a execução do projeto

2023-05-09 02:26 UTC, ViniciusAcordiSoethe approved these changes
Approved, the issues are all resolve

2023-05-09 02:27 UTC, merged